spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://lead-management-mysql:3306/lead_management}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:your_password}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false

server.port=8081

jwt.secret=${JWT_SECRET:bXktc3VwZXItc2VjcmV0LWtleS1teS1zdXBlci1zZWNyZXQta2V5LW11c3QtYmUtbG9uZw==}
jwt.expiration=3600000

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=never